# ~/.zshrc — interactive shells: prompt, completion, history.
# Source of truth: /Users/Shared/dotfiles (symlinked into ~).

# Powerlevel10k instant prompt — keep at the very top, before any output.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

ZSH_SHARED="/Users/Shared/dotfiles/zsh"

# Completion system
autoload -Uz compinit && compinit

# Prompt theme
source "$ZSH_SHARED/powerlevel10k/powerlevel10k.zsh-theme"

# History (HISTFILE is per-account — never shared)
HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=50000
setopt HIST_IGNORE_DUPS HIST_IGNORE_SPACE HIST_REDUCE_BLANKS SHARE_HISTORY

# Colors (macOS default `ls` palette)
export CLICOLOR=1

# Prompt config (generated by `p10k configure`)
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

# >>> tool init (managed by the `dotfiles` skill — all guarded) >>>
# (empty — add a tool's guarded init here, e.g. via: /dotfiles)
# <<< tool init <<<

# Per-account overrides (NOT shared): work git email, account-only tools, etc.
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
